package eu.ortlepp.blogbuilder.gui;

import java.io.Serializable;

/**
 * The controller for the GUI window. Manages all actions triggered in the GUI.
 *
 * @author Thorsten Ortlepp
 */
class Controller implements Serializable {

    /** Serial Version UID. Generated by Eclipse IDE. */
    private static final long serialVersionUID = 1947826455012037689L;

    /** The project that is currently opened. Empty if no project is opened. */
    private String project;


    /**
     * Constructor, initializes the controller.
     */
    public Controller() {
        project = "";
    }


    /**
     * Getter for the currently opened project. Returns "none" in case no project is open.
     *
     * @return The currently opened project
     */
    public String getProject() {
        if (project.isEmpty()) {
            return "none";
        }
        return project;
    }


    /**
     * Setter for the currently opened project.
     *
     * @param project The currently opened project
     */
    public void setProject(final String project) {
        this.project = project;
    }


    /**
     * Run the initialization action.
     */
    public void runInitialization() {
        if (!project.isEmpty()) {
            System.out.println("INIT...");
        }
    }


    /**
     * Run the build action.
     */
    public void runBuild() {
        if (!project.isEmpty()) {
            System.out.println("BUILD...");
        }
    }

}
